from typing import Any

class MockJikanFetcher:
    def fetch_data_by_title(self, anime_title: str = "Attack on titan", entry_number: int = 0) -> list[dict[str, Any]]:
        return [{'aired': {'from': '2013-04-07T00:00:00+00:00',
                            'prop': {'from': {'day': 7, 'month': 4, 'year': 2013},
                                    'to': {'day': 29, 'month': 9, 'year': 2013}},
                            'string': 'Apr 7, 2013 to Sep 29, 2013',
                            'to': '2013-09-29T00:00:00+00:00'},
                'airing': False,
                'approved': True,
                'background': 'Shingeki no Kyojin adapts content from the first eight '
                                "volumes of Hajime Isayama's award-winning manga of the same "
                                'name. The anime won the Animation of the Year in the '
                                'Television category at the Tokyo Anime Award Festival in '
                                '2014.',
                'broadcast': {'day': 'Sundays',
                                'string': 'Sundays at 01:58 (JST)',
                                'time': '01:58',
                                'timezone': 'Asia/Tokyo'},
                'demographics': [{'mal_id': 27,
                                    'name': 'Shounen',
                                    'type': 'anime',
                                    'url': 'https://myanimelist.net/anime/genre/27/Shounen'}],
                'duration': '24 min per ep',
                'episodes': 25,
                'explicit_genres': [],
                'favorites': 188246,
                'genres': [{'mal_id': 1,
                            'name': 'Action',
                            'type': 'anime',
                            'url': 'https://myanimelist.net/anime/genre/1/Action'},
                            {'mal_id': 46,
                            'name': 'Award Winning',
                            'type': 'anime',
                            'url': 'https://myanimelist.net/anime/genre/46/Award_Winning'},
                            {'mal_id': 8,
                            'name': 'Drama',
                            'type': 'anime',
                            'url': 'https://myanimelist.net/anime/genre/8/Drama'},
                            {'mal_id': 41,
                            'name': 'Suspense',
                            'type': 'anime',
                            'url': 'https://myanimelist.net/anime/genre/41/Suspense'}],
                'images': {'jpg': {'image_url': 'https://myanimelist.net/images/anime/10/47347.jpg',
                                    'large_image_url': 'https://myanimelist.net/images/anime/10/47347l.jpg',
                                    'small_image_url': 'https://myanimelist.net/images/anime/10/47347t.jpg'},
                            'webp': {'image_url': 'https://myanimelist.net/images/anime/10/47347.webp',
                                    'large_image_url': 'https://myanimelist.net/images/anime/10/47347l.webp',
                                    'small_image_url': 'https://myanimelist.net/images/anime/10/47347t.webp'}},
                'licensors': [{'mal_id': 102,
                                'name': 'Funimation',
                                'type': 'anime',
                                'url': 'https://myanimelist.net/anime/producer/102/Funimation'}],
                'mal_id': 16498,
                'members': 4342029,
                'popularity': 1,
                'producers': [{'mal_id': 10,
                                'name': 'Production I.G',
                                'type': 'anime',
                                'url': 'https://myanimelist.net/anime/producer/10/Production_IG'},
                                {'mal_id': 53,
                                'name': 'Dentsu',
                                'type': 'anime',
                                'url': 'https://myanimelist.net/anime/producer/53/Dentsu'},
                                {'mal_id': 143,
                                'name': 'Mainichi Broadcasting System',
                                'type': 'anime',
                                'url': 'https://myanimelist.net/anime/producer/143/Mainichi_Broadcasting_System'},
                                {'mal_id': 144,
                                'name': 'Pony Canyon',
                                'type': 'anime',
                                'url': 'https://myanimelist.net/anime/producer/144/Pony_Canyon'},
                                {'mal_id': 159,
                                'name': 'Kodansha',
                                'type': 'anime',
                                'url': 'https://myanimelist.net/anime/producer/159/Kodansha'},
                                {'mal_id': 1557,
                                'name': 'Pony Canyon Enterprises',
                                'type': 'anime',
                                'url': 'https://myanimelist.net/anime/producer/1557/Pony_Canyon_Enterprises'}],
                'rank': 125,
                'rating': 'R - 17+ (violence & profanity)',
                'score': 8.57,
                'scored_by': 3056005,
                'season': 'spring',
                'source': 'Manga',
                'status': 'Finished Airing',
                'studios': [{'mal_id': 858,
                            'name': 'Wit Studio',
                            'type': 'anime',
                            'url': 'https://myanimelist.net/anime/producer/858/Wit_Studio'}],
                'synopsis': 'Centuries ago, mankind was slaughtered to near extinction by '
                            'monstrous humanoid creatures called Titans, forcing humans to '
                            'hide in fear behind enormous concentric walls. What makes these '
                            'giants truly terrifying is that their taste for human flesh is '
                            'not born out of hunger but what appears to be out of pleasure. '
                            'To ensure their survival, the remnants of humanity began living '
                            'within defensive barriers, resulting in one hundred years '
                            'without a single titan encounter. However, that fragile calm is '
                            'soon shattered when a colossal Titan manages to breach the '
                            'supposedly impregnable outer wall, reigniting the fight for '
                            'survival against the man-eating abominations.\n'
                            '\n'
                            'After witnessing a horrific personal loss at the hands of the '
                            'invading creatures, Eren Yeager dedicates his life to their '
                            'eradication by enlisting into the Survey Corps, an elite '
                            'military unit that combats the merciless humanoids outside the '
                            'protection of the walls. Eren, his adopted sister Mikasa '
                            'Ackerman, and his childhood friend Armin Arlert join the brutal '
                            'war against the Titans and race to discover a way of defeating '
                            'them before the last walls are breached.\n'
                            '\n'
                            '[Written by MAL Rewrite]',
                'themes': [{'mal_id': 58,
                            'name': 'Gore',
                            'type': 'anime',
                            'url': 'https://myanimelist.net/anime/genre/58/Gore'},
                            {'mal_id': 38,
                            'name': 'Military',
                            'type': 'anime',
                            'url': 'https://myanimelist.net/anime/genre/38/Military'},
                            {'mal_id': 76,
                            'name': 'Survival',
                            'type': 'anime',
                            'url': 'https://myanimelist.net/anime/genre/76/Survival'}],
                'title': 'Shingeki no Kyojin',
                'title_english': 'Attack on Titan',
                'title_japanese': '進撃の巨人',
                'title_synonyms': ['AoT', 'SnK'],
                'titles': [{'title': 'Shingeki no Kyojin', 'type': 'Default'},
                            {'title': 'AoT', 'type': 'Synonym'},
                            {'title': 'SnK', 'type': 'Synonym'},
                            {'title': '進撃の巨人', 'type': 'Japanese'},
                            {'title': 'Attack on Titan', 'type': 'English'},
                            {'title': 'Attack on Titan', 'type': 'German'},
                            {'title': 'Ataque a los Titanes', 'type': 'Spanish'},
                            {'title': "L'Attaque des Titans", 'type': 'French'}],
                'trailer': {'embed_url': 'https://www.youtube-nocookie.com/embed/LHtdKWJdif4?enablejsapi=1&wmode=opaque&autoplay=1',
                            'images': {'image_url': None,
                                        'large_image_url': None,
                                        'maximum_image_url': None,
                                        'medium_image_url': None,
                                        'small_image_url': None},
                            'url': None,
                            'youtube_id': None},
                'type': 'TV',
                'url': 'https://myanimelist.net/anime/16498/Shingeki_no_Kyojin',
                'year': 2013},
                {'aired': {'from': '2017-04-10T00:00:00+00:00',
                            'prop': {'from': {'day': 10, 'month': 4, 'year': 2017},
                                    'to': {'day': None, 'month': None, 'year': None}},
                            'string': 'Apr 10, 2017',
                            'to': None},
                'airing': False,
                'approved': True,
                'background': '',
                'broadcast': {'day': None, 'string': None, 'time': None, 'timezone': None},
                'demographics': [{'mal_id': 27,
                                    'name': 'Shounen',
                                    'type': 'anime',
                                    'url': 'https://myanimelist.net/anime/genre/27/Shounen'}],
                'duration': '7 min',
                'episodes': 1,
                'explicit_genres': [],
                'favorites': 88,
                'genres': [{'mal_id': 1,
                            'name': 'Action',
                            'type': 'anime',
                            'url': 'https://myanimelist.net/anime/genre/1/Action'},
                            {'mal_id': 10,
                            'name': 'Fantasy',
                            'type': 'anime',
                            'url': 'https://myanimelist.net/anime/genre/10/Fantasy'}],
                'images': {'jpg': {'image_url': 'https://myanimelist.net/images/anime/3/84716.jpg',
                                    'large_image_url': 'https://myanimelist.net/images/anime/3/84716l.jpg',
                                    'small_image_url': 'https://myanimelist.net/images/anime/3/84716t.jpg'},
                            'webp': {'image_url': 'https://myanimelist.net/images/anime/3/84716.webp',
                                    'large_image_url': 'https://myanimelist.net/images/anime/3/84716l.webp',
                                    'small_image_url': 'https://myanimelist.net/images/anime/3/84716t.webp'}},
                'licensors': [],
                'mal_id': 35122,
                'members': 27537,
                'popularity': 4841,
                'producers': [{'mal_id': 159,
                                'name': 'Kodansha',
                                'type': 'anime',
                                'url': 'https://myanimelist.net/anime/producer/159/Kodansha'}],
                'rank': 8706,
                'rating': 'PG-13 - Teens 13 or older',
                'score': 6.38,
                'scored_by': 7958,
                'season': None,
                'source': 'Manga',
                'status': 'Finished Airing',
                'studios': [],
                'synopsis': 'A special anime featuring a battle against the Colossal Titan '
                            'screened at the Tokyo Skytree.\n'
                            '\n'
                            'In the short, the characters from Shingeki no Kyojin are part '
                            'of the Sky Survey Corps, protecting the Wall Skytree, a section '
                            'of the walled city that contains the Skytree. The Sky Survey '
                            'Corps find that the Wall Skytree is under attack by an army of '
                            'titans, including a giant 350 meter-class titan that has '
                            'suddenly appeared next to the Skytree and remains motionless.\n'
                            '\n'
                            '(Source: Anime Now!)',
                'themes': [],
                'title': 'Shingeki no Kyotou',
                'title_english': 'Attack on Skytree',
                'title_japanese': '進撃の巨塔',
                'title_synonyms': ['Shingeki no Kyojin: Attack on Skytree',
                                    'Attack on Titan'],
                'titles': [{'title': 'Shingeki no Kyotou', 'type': 'Default'},
                            {'title': 'Shingeki no Kyojin: Attack on Skytree',
                            'type': 'Synonym'},
                            {'title': 'Attack on Titan', 'type': 'Synonym'},
                            {'title': '進撃の巨塔', 'type': 'Japanese'},
                            {'title': 'Attack on Skytree', 'type': 'English'}],
                'trailer': {'embed_url': None,
                            'images': {'image_url': None,
                                        'large_image_url': None,
                                        'maximum_image_url': None,
                                        'medium_image_url': None,
                                        'small_image_url': None},
                            'url': None,
                            'youtube_id': None},
                'type': 'Movie',
                'url': 'https://myanimelist.net/anime/35122/Shingeki_no_Kyotou',
                'year': None},
                {'aired': {'from': '2024-11-08T00:00:00+00:00',
                            'prop': {'from': {'day': 8, 'month': 11, 'year': 2024},
                                    'to': {'day': None, 'month': None, 'year': None}},
                            'string': 'Nov 8, 2024',
                            'to': None},
                'airing': False,
                'approved': True,
                'background': '',
                'broadcast': {'day': None, 'string': None, 'time': None, 'timezone': None},
                'demographics': [{'mal_id': 27,
                                    'name': 'Shounen',
                                    'type': 'anime',
                                    'url': 'https://myanimelist.net/anime/genre/27/Shounen'}],
                'duration': '2 hr 24 min',
                'episodes': 1,
                'explicit_genres': [],
                'favorites': 622,
                'genres': [{'mal_id': 1,
                            'name': 'Action',
                            'type': 'anime',
                            'url': 'https://myanimelist.net/anime/genre/1/Action'},
                            {'mal_id': 8,
                            'name': 'Drama',
                            'type': 'anime',
                            'url': 'https://myanimelist.net/anime/genre/8/Drama'},
                            {'mal_id': 41,
                            'name': 'Suspense',
                            'type': 'anime',
                            'url': 'https://myanimelist.net/anime/genre/41/Suspense'}],
                'images': {'jpg': {'image_url': 'https://myanimelist.net/images/anime/1379/145452.jpg',
                                    'large_image_url': 'https://myanimelist.net/images/anime/1379/145452l.jpg',
                                    'small_image_url': 'https://myanimelist.net/images/anime/1379/145452t.jpg'},
                            'webp': {'image_url': 'https://myanimelist.net/images/anime/1379/145452.webp',
                                    'large_image_url': 'https://myanimelist.net/images/anime/1379/145452l.webp',
                                    'small_image_url': 'https://myanimelist.net/images/anime/1379/145452t.webp'}},
                'licensors': [],
                'mal_id': 59571,
                'members': 85512,
                'popularity': 2639,
                'producers': [{'mal_id': 144,
                                'name': 'Pony Canyon',
                                'type': 'anime',
                                'url': 'https://myanimelist.net/anime/producer/144/Pony_Canyon'}],
                'rank': 32,
                'rating': 'R - 17+ (violence & profanity)',
                'score': 8.83,
                'scored_by': 39528,
                'season': None,
                'source': 'Manga',
                'status': 'Finished Airing',
                'studios': [{'mal_id': 569,
                            'name': 'MAPPA',
                            'type': 'anime',
                            'url': 'https://myanimelist.net/anime/producer/569/MAPPA'}],
                'synopsis': 'A compilation movie for Shingeki no Kyojin: The Final Season - '
                            'Kanketsu-hen.',
                'themes': [{'mal_id': 58,
                            'name': 'Gore',
                            'type': 'anime',
                            'url': 'https://myanimelist.net/anime/genre/58/Gore'},
                            {'mal_id': 38,
                            'name': 'Military',
                            'type': 'anime',
                            'url': 'https://myanimelist.net/anime/genre/38/Military'},
                            {'mal_id': 76,
                            'name': 'Survival',
                            'type': 'anime',
                            'url': 'https://myanimelist.net/anime/genre/76/Survival'}],
                'title': 'Shingeki no Kyojin Movie: Kanketsu-hen - The Last Attack',
                'title_english': 'Attack on Titan: The Last Attack',
                'title_japanese': '劇場版 進撃の巨人 完結編 THE LAST ATTACK',
                'title_synonyms': ['Attack on Titan the Movie: The Last Attack'],
                'titles': [{'title': 'Shingeki no Kyojin Movie: Kanketsu-hen - The Last '
                                    'Attack',
                            'type': 'Default'},
                            {'title': 'Attack on Titan the Movie: The Last Attack',
                            'type': 'Synonym'},
                            {'title': '劇場版 進撃の巨人 完結編 THE LAST ATTACK', 'type': 'Japanese'},
                            {'title': 'Attack on Titan: The Last Attack', 'type': 'English'}],
                'trailer': {'embed_url': 'https://www.youtube-nocookie.com/embed/PuE1uRbpkTk?enablejsapi=1&wmode=opaque&autoplay=1',
                            'images': {'image_url': None,
                                        'large_image_url': None,
                                        'maximum_image_url': None,
                                        'medium_image_url': None,
                                        'small_image_url': None},
                            'url': None,
                            'youtube_id': None},
                'type': 'Movie',
                'url': 'https://myanimelist.net/anime/59571/Shingeki_no_Kyojin_Movie__Kanketsu-hen_-_The_Last_Attack',
                'year': None}]

    def fetch_data_by_id(self, anime_id: int = 16498) -> dict[str, Any]:
        return {'aired': {'from': '2013-04-07T00:00:00+00:00',
                'prop': {'from': {'day': 7, 'month': 4, 'year': 2013},
                            'to': {'day': 29, 'month': 9, 'year': 2013}},
                'string': 'Apr 7, 2013 to Sep 29, 2013',
                'to': '2013-09-29T00:00:00+00:00'},
        'airing': False,
        'approved': True,
        'background': 'Shingeki no Kyojin adapts content from the first eight volumes '
                    "of Hajime Isayama's award-winning manga of the same name. The "
                    'anime won the Animation of the Year in the Television category '
                    'at the Tokyo Anime Award Festival in 2014.',
        'broadcast': {'day': 'Sundays',
                    'string': 'Sundays at 01:58 (JST)',
                    'time': '01:58',
                    'timezone': 'Asia/Tokyo'},
        'demographics': [{'mal_id': 27,
                        'name': 'Shounen',
                        'type': 'anime',
                        'url': 'https://myanimelist.net/anime/genre/27/Shounen'}],
        'duration': '24 min per ep',
        'episodes': 25,
        'explicit_genres': [],
        'favorites': 188134,
        'genres': [{'mal_id': 1,
                    'name': 'Action',
                    'type': 'anime',
                    'url': 'https://myanimelist.net/anime/genre/1/Action'},
                    {'mal_id': 46,
                    'name': 'Award Winning',
                    'type': 'anime',
                    'url': 'https://myanimelist.net/anime/genre/46/Award_Winning'},
                    {'mal_id': 8,
                    'name': 'Drama',
                    'type': 'anime',
                    'url': 'https://myanimelist.net/anime/genre/8/Drama'},
                    {'mal_id': 41,
                    'name': 'Suspense',
                    'type': 'anime',
                    'url': 'https://myanimelist.net/anime/genre/41/Suspense'}],
        'images': {'jpg': {'image_url': 'https://myanimelist.net/images/anime/10/47347.jpg',
                            'large_image_url': 'https://myanimelist.net/images/anime/10/47347l.jpg',
                            'small_image_url': 'https://myanimelist.net/images/anime/10/47347t.jpg'},
                    'webp': {'image_url': 'https://myanimelist.net/images/anime/10/47347.webp',
                            'large_image_url': 'https://myanimelist.net/images/anime/10/47347l.webp',
                            'small_image_url': 'https://myanimelist.net/images/anime/10/47347t.webp'}},
        'licensors': [{'mal_id': 102,
                        'name': 'Funimation',
                        'type': 'anime',
                        'url': 'https://myanimelist.net/anime/producer/102/Funimation'}],
        'mal_id': 16498,
        'members': 4338901,
        'popularity': 1,
        'producers': [{'mal_id': 10,
                        'name': 'Production I.G',
                        'type': 'anime',
                        'url': 'https://myanimelist.net/anime/producer/10/Production_IG'},
                    {'mal_id': 53,
                        'name': 'Dentsu',
                        'type': 'anime',
                        'url': 'https://myanimelist.net/anime/producer/53/Dentsu'},
                    {'mal_id': 143,
                        'name': 'Mainichi Broadcasting System',
                        'type': 'anime',
                        'url': 'https://myanimelist.net/anime/producer/143/Mainichi_Broadcasting_System'},
                    {'mal_id': 144,
                        'name': 'Pony Canyon',
                        'type': 'anime',
                        'url': 'https://myanimelist.net/anime/producer/144/Pony_Canyon'},
                    {'mal_id': 159,
                        'name': 'Kodansha',
                        'type': 'anime',
                        'url': 'https://myanimelist.net/anime/producer/159/Kodansha'},
                    {'mal_id': 1557,
                        'name': 'Pony Canyon Enterprises',
                        'type': 'anime',
                        'url': 'https://myanimelist.net/anime/producer/1557/Pony_Canyon_Enterprises'}],
        'rank': 124,
        'rating': 'R - 17+ (violence & profanity)',
        'score': 8.57,
        'scored_by': 3053718,
        'season': 'spring',
        'source': 'Manga',
        'status': 'Finished Airing',
        'studios': [{'mal_id': 858,
                    'name': 'Wit Studio',
                    'type': 'anime',
                    'url': 'https://myanimelist.net/anime/producer/858/Wit_Studio'}],
        'synopsis': 'Centuries ago, mankind was slaughtered to near extinction by '
                    'monstrous humanoid creatures called Titans, forcing humans to '
                    'hide in fear behind enormous concentric walls. What makes these '
                    'giants truly terrifying is that their taste for human flesh is '
                    'not born out of hunger but what appears to be out of pleasure. '
                    'To ensure their survival, the remnants of humanity began living '
                    'within defensive barriers, resulting in one hundred years '
                    'without a single titan encounter. However, that fragile calm is '
                    'soon shattered when a colossal Titan manages to breach the '
                    'supposedly impregnable outer wall, reigniting the fight for '
                    'survival against the man-eating abominations.\n'
                    '\n'
                    'After witnessing a horrific personal loss at the hands of the '
                    'invading creatures, Eren Yeager dedicates his life to their '
                    'eradication by enlisting into the Survey Corps, an elite '
                    'military unit that combats the merciless humanoids outside the '
                    'protection of the walls. Eren, his adopted sister Mikasa '
                    'Ackerman, and his childhood friend Armin Arlert join the brutal '
                    'war against the Titans and race to discover a way of defeating '
                    'them before the last walls are breached.\n'
                    '\n'
                    '[Written by MAL Rewrite]',
        'themes': [{'mal_id': 58,
                    'name': 'Gore',
                    'type': 'anime',
                    'url': 'https://myanimelist.net/anime/genre/58/Gore'},
                    {'mal_id': 38,
                    'name': 'Military',
                    'type': 'anime',
                    'url': 'https://myanimelist.net/anime/genre/38/Military'},
                    {'mal_id': 76,
                    'name': 'Survival',
                    'type': 'anime',
                    'url': 'https://myanimelist.net/anime/genre/76/Survival'}],
        'title': 'Shingeki no Kyojin',
        'title_english': 'Attack on Titan',
        'title_japanese': '進撃の巨人',
        'title_synonyms': ['AoT', 'SnK'],
        'titles': [{'title': 'Shingeki no Kyojin', 'type': 'Default'},
                    {'title': 'AoT', 'type': 'Synonym'},
                    {'title': 'SnK', 'type': 'Synonym'},
                    {'title': '進撃の巨人', 'type': 'Japanese'},
                    {'title': 'Attack on Titan', 'type': 'English'},
                    {'title': 'Attack on Titan', 'type': 'German'},
                    {'title': 'Ataque a los Titanes', 'type': 'Spanish'},
                    {'title': "L'Attaque des Titans", 'type': 'French'}],
        'trailer': {'embed_url': 'https://www.youtube-nocookie.com/embed/LHtdKWJdif4?enablejsapi=1&wmode=opaque&autoplay=1',
                    'images': {'image_url': None,
                                'large_image_url': None,
                                'maximum_image_url': None,
                                'medium_image_url': None,
                                'small_image_url': None},
                    'url': None,
                    'youtube_id': None},
        'type': 'TV',
        'url': 'https://myanimelist.net/anime/16498/Shingeki_no_Kyojin',
        'year': 2013}
        
class MockAnilistFetcher:
    def fetch_data_by_title(self, anime_title: str = "Attack on titan") -> list[dict[str, Any]]:
        return [{'averageScore': 85,
                'episodes': 25,
                'genres': ['Action', 'Drama', 'Fantasy', 'Mystery'],
                'id': 16498,
                'title': {'english': 'Attack on Titan', 'romaji': 'Shingeki no Kyojin'}},
                {'averageScore': 77,
                'episodes': 3,
                'genres': ['Action', 'Drama', 'Fantasy', 'Mystery'],
                'id': 18397,
                'title': {'english': 'Attack on Titan OVA',
                            'romaji': 'Shingeki no Kyojin OVA'}},
                {'averageScore': 87,
                'episodes': 16,
                'genres': ['Action', 'Drama', 'Fantasy', 'Mystery'],
                'id': 110277,
                'title': {'english': 'Attack on Titan Final Season',
                            'romaji': 'Shingeki no Kyojin: The Final Season'}},
                {'averageScore': 83,
                'episodes': 2,
                'genres': ['Action', 'Drama', 'Fantasy'],
                'id': 20811,
                'title': {'english': 'Attack on Titan: No Regrets',
                            'romaji': 'Shingeki no Kyojin Gaiden: Kuinaki Sentaku'}},
                {'averageScore': 85,
                'episodes': 12,
                'genres': ['Action', 'Drama', 'Fantasy', 'Mystery'],
                'id': 20958,
                'title': {'english': 'Attack on Titan Season 2',
                            'romaji': 'Shingeki no Kyojin Season 2'}},
                {'averageScore': 86,
                'episodes': 12,
                'genres': ['Action', 'Drama', 'Fantasy', 'Mystery'],
                'id': 99147,
                'title': {'english': 'Attack on Titan Season 3',
                            'romaji': 'Shingeki no Kyojin Season 3'}},
                {'averageScore': 77,
                'episodes': 1,
                'genres': ['Action', 'Drama', 'Fantasy', 'Mystery'],
                'id': 119113,
                'title': {'english': 'Attack on Titan ~Chronicle~',
                            'romaji': 'Shingeki no Kyojin: Chronicle'}},
                {'averageScore': 63,
                'episodes': 9,
                'genres': ['Action', 'Comedy', 'Drama', 'Fantasy'],
                'id': 19391,
                'title': {'english': 'Attack on Titan Picture Drama',
                            'romaji': 'Shingeki no Kyojin: Chimi Kyara Gekijou - Tondeke! '
                                    'Kunren Heidan'}},
                {'averageScore': 77,
                'episodes': 3,
                'genres': ['Action', 'Drama', 'Fantasy', 'Mystery'],
                'id': 99634,
                'title': {'english': 'Attack on Titan: Lost Girls',
                            'romaji': 'Shingeki no Kyojin: LOST GIRLS'}},
                {'averageScore': 70,
                'episodes': 12,
                'genres': ['Comedy', 'Fantasy', 'Slice of Life'],
                'id': 21281,
                'title': {'english': 'Attack on Titan: Junior High',
                            'romaji': 'Shingeki! Kyojin Chuugakkou'}}]
    
    def fetch_data_by_id(self, anime_id: int = 16498) -> dict[str, Any]:
        return {'averageScore': 85,
                'episodes': 25,
                'genres': ['Action', 'Drama', 'Fantasy', 'Mystery'],
                'id': 16498,
                'title': {'english': 'Attack on Titan', 'romaji': 'Shingeki no Kyojin'}}